version: "3.9"

services:

  db:
    image: mysql:8.0
    container_name: kochbuch-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"


  backend:
    build: ./backend
    container_name: kochbuch-backend-cd
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: kochbuch
      MYSQL_USER: appuser
      MYSQL_PASSWORD: secret
    depends_on:
      - db
    # Backend nur im internen Netzwerk, kein Port nach außen nötig
    # ports:
    #   - "8081:8080"
    networks:
      - kochbuch-net

  frontend:
    build: ./frontend
    container_name: kochbuch-frontend-cd
    depends_on:
      - backend
    ports:
      - "8080:80"   # Browser -> Frontend
    networks:
      - kochbuch-net

networks:
  kochbuch-net:

volumes:
  db_data:
